#' Generate Template Information from Raw Excel Template
#'
#' The `generate_template` function reads in a raw data file template, typically generated
#' by `read_excel_all`, and creates a structured template that can be used to interpret a
#' given version of that particular form. It provides a streamlined approach to
#' extract data from structured forms where templates can be used to identify the
#' location and meaning of data elements.
#'
#' @param raw_template A data frame, typically generated by `read_excel_all`,
#'   representing the raw structure of the form template. This template
#'   contains tags to indicate data locations and metadata.
#'
#' @return A named list containing:
#'   * `variable_info`: A data frame documenting the location of single-cell variables.
#'   * `table_info`: A data frame documenting the location and name of tables.
#'   * `column_info`: A data frame that lists tables and their column names.
#'
#' @seealso [read_excel_all()]
#'
#' @examples
#' \dontrun{
#'   raw <- read_excel_all("path_to_template.xlsx")
#'   template_data <- generate_template(raw)
#'   print(template_data$variable_info)
#' }
#'
#' @export
generate_template <- function (raw_template) {
  list(list ("variable_info" = variable_info(raw_template)),

       tables_and_columns (raw_template)) %>%
    purrr::flatten() %>%
    purrr::map(list) %>%
    tibble::as_tibble()
}
